### PR TITLE
second question's answer

### PR DESCRIPTION
**Pull request by smyybtmz**

### CODE REVIEW

**Comment by xiuhead92** [comment]
its good!

**Review by betulperco — APPROVED** [review]
its fine

**Comment by eyup1312** [comment]
fine

**Review by xiuhead92 — APPROVED** [review]

**Review by eyup1312 — APPROVED** [review]

**Comment by eyup1312** [comment]
fine

**Review by fahriozcan — APPROVED** [review]

**Comment by Emretester** [comment]
Looks good

**Pull request merged**
