### PR TITLE
EmreBranch

### PR DESCRIPTION
**Pull request by Emretester**

### CODE REVIEW

**Comment by fahriozcan** [comment]
wants to merge 1 commit into [master](https://github.com/fahriozcan/Group5Java/tree/master) from [EmreBranch](https://github.com/fahriozcan/Group5Java/tree/EmreBranch) . You created your pull request from your own branch to master branch directly which is not allowed. You need to make it from your branch to develop branch

**Review by tscselma — APPROVED** [review]

**Review by betulperco — APPROVED** [review]
they are fine

**Comment by smyybtmz** [comment]
Looks good!

**Comment by Emretester** [comment]
> wants to merge 1 commit into [master](https://github.com/fahriozcan/Group5Java/tree/master) from [EmreBranch](https://github.com/fahriozcan/Group5Java/tree/EmreBranch) . You created your pull request from your own branch to master branch directly which is not allowed. You need to make it from your branch to develop branch

Could you please align me to "develop" branch? I don't have any information about it.

**Pull request closed without merging**
