### PR TITLE
Lala's first project

### PR DESCRIPTION
**Pull request by lalesi85**
I created my first class

### CODE REVIEW

**Review by xiuhead92 — CHANGES_REQUESTED** [review]
week 1, question 1 (Xenia)

**Comment by tscselma** [comment]
hope i could do it

**Review by fahriozcan — APPROVED** [review]
It is done

**Review by betulperco — APPROVED** [review]
Its fine Lala

**Review by eyup1312 — APPROVED** [review]

**Comment by eyup1312** [comment]
all good

**Review by xiuhead92 — APPROVED** [review]

**Pull request merged**
